
version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=5005
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    