services:
  vitereactshadcnts:
    image: vitereactshadcnts
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3443:3443
